### ISSUE TITLE
peer's sigs  does not match a commit tx in local unilateral close

### ISSUE THREAD

**Issue by nayuta-gondo** [nayutaco/ptarmigan#1313]

**Comment by nayuta-gondo** [comment]
ピアの署名がおかしいのではなく、作成したcommit txが想定したものと違う。
詳細は忘れたが、とにかく前回の`commitment_signed`を受信した後に別のメッセージを受信したからでだったと記憶している。
現行の実装ではcommit txを作る処理が`commitment_signed`受信直前の状態を前提にして次のバージョンのcommit txが作られることに留意すること。
どのようなメッセージ受信が影響するかというと、
1. `update`受信
これは除外しなければいけない。
1. `revoke_and_ack`受信
このタイミングでlocal commit txに落ちたupdateがcommit tx作成時に反映されてしまう。
これも除外しなければいけない。

２つの対応案として
1. 状態をrewindする
1. commitされていないものは反映されないcommit tx作成処理を作成する。
前述の通り、現在は次にcommitされる予定のものも反映される。

**Comment by nayuta-ueno** [comment]
#814 ？

**Comment by nayuta-gondo** [comment]
あ、それね
相手があることなので安定を待ってというのはできない可能性がある。

**Comment by nayuta-gondo** [comment]
#1330　で「2」は修正
「1」は#1331　にissueを分けた
