### ISSUE TITLE
unexpected revoke_and_ack

### ISSUE THREAD

**Issue by nayuta-ueno** [nayutaco/ptarmigan#1319]
commit 98aa542ba67bfc73e2dc07e86d7d452021a14c04

# prepare

* c-lightning build with developer mode

```bash
./configure --enable-developer
```

* create disconnect file
  * `test.txt`

```text
-WIRE_UPDATE_FULFILL_HTLC
```

# procedure

1. start c-lightning

```bash
./lightningd/lightningd --network=regtest --lightning-dir=./something_test_dir --dev-disconnect=`pwd`/test.txt --dev-no-reconnect --log-level=debug
```

2. start ptarmigan
3. connect and open channel
4. [cln]get invoice
5. [ptarm]pay

# result

* disconnect before `update_fulfill_htlc` (OK)
* reconnect from ptarmigan (OK)
* exchange `init` and `channel_reestablish` (OK)
* c-lightning send `update_fulfill_htlc` and `commitment_signed`, ptarmigan send `revoke_and_ack` (maybe OK)
* ptarmigan send `revoke_and_ack` (NG : unexpected revoke_and_ack)

**Comment by nayuta-gondo** [comment]
channel_reestablishのあとにrevoke_and_ackの再送は不要な状況なのに、ln_channel_reestablish_afterで再送が必要かチェックする前に、
>c-lightning send update_fulfill_htlc and commitment_signed, ptarmigan send revoke_and_ack (maybe OK)
が発生し、チェックを間違えてしまっている。
