### ISSUE TITLE
REST API sendpayment doesn't do anything

### ISSUE THREAD

**Issue by fiatjaf** [nayutaco/ptarmigan#1441]
Hey, trying to use the `sendpayment` method in the REST API returns a blank response (which contains only an id and no `error` nor `result`). Also the invoice doesn't get paid at all:

```
fiatjaf@menger ~/p/ptarmapi (master)>                                                                     
curl -X POST -H 'content-type: application/json' http://localhost:3000/sendpayment -d '{"bolt11": "lnbcrt6
549870p1pwv37g5pp58jyq6efwuavmeutzm07synpfyrgrxg9vj32ttc8pwchyjgszvd3qdqjddshx6nydeskkum2vsxqrrsshutkyftcg
fsmsxcd2nmqz8mgx3g4tsghrvjnh5lkrpwjvzv6ffljhgejcvh7h8m2vaaj9a8raxhqhkh97ll34x8ckf6ragyufwnremcpahe58x"}   
'                                                                                                         
{"id":"d75214d3-f26e-42d5-b712-ca95ae39ab1f"}
```

Doing the same with `ptarmcli --sendpayment` works fine.

**Comment by nayuta-gondo** [comment]
please add `, "addAmountMsat": 0`
'''
curl -X POST -H 'content-type: application/json' http://localhost:3000/sendpayment -d '{"bolt11": "lnbc1880n1pwv5lzmpp52utq4hmctklzxm0hmnh7gp02chv7uudzkqds6a8hamvqe0kjtp8sdzg2pskjepqw3hjqnnp096hgcfqf35kw6r5de5kueeq2d5x7upq9p8hyer9wgsyj3p6yqenxwffxqzurcqp2rzjq2qfaym0p6pdlnsnhnz8cac39kcx3atfu8djnealnz7d669c8rhggz9k4gqq4mqqqqqqqqqqqqqqqeqq9q30ulj44qw3lnlluszaea6wk87nlpvpwq0jy85dh769jl6dn34yeqdqu6aa0dufehxq7s63kktp482vmuegdtsdakakujjz6pael43eqq96nd6m", "addAmountMsat": 0}'
'''

**Comment by nayuta-gondo** [comment]
Since ｀sendpayment` makes payments asynchronously, it returns `payment_id` first.
```
{"result":{"payment_id":6},"id":"c024e8b4-8a72-4850-9c05-634ad78d159d"}
```

**Comment by nayuta-gondo** [comment]
The status of the payment can be confirmed by `listpayments`
```
curl -X POST -H 'content-type: application/json' http://localhost:3000/listpayments
```
```
{
  "result": [
    {
      "payment_id": 6,
      "payment_hash": "57160adf785dbe236df7dcefe405eac5d9ee71a2b01b0d74f7eed80cbed2584f",
      "preimage": "***********************************************",
      "additional_amount_msat": 0,
      "block_count": 574204,
      "retry_count": 4,
      "max_retry_count": 10,
      "auto_remove": "false",
      "state": "succeeded",
      "invoice": "lnbc1880n1pwv5lzmpp52utq4hmctklzxm0hmnh7gp02chv7uudzkqds6a8hamvqe0kjtp8sdzg2pskjepqw3hjqnnp096hgcfqf35kw6r5de5kueeq2d5x7upq9p8hyer9wgsyj3p6yqenxwffxqzurcqp2rzjq2qfaym0p6pdlnsnhnz8cac39kcx3atfu8djnealnz7d669c8rhggz9k4gqq4mqqqqqqqqqqqqqqqeqq9q30ulj44qw3lnlluszaea6wk87nlpvpwq0jy85dh769jl6dn34yeqdqu6aa0dufehxq7s63kktp482vmuegdtsdakakujjz6pael43eqq96nd6m"
    }
  ],
  "id": "7ee1f78f-0b78-4d05-8def-97506e81d77b"
}
```
`state` is `processing`, `succeeded`, or `failed`

**Comment by nayuta-gondo** [comment]
It is a bug that an error is not returned when there is no `addAmountMsat`.
We are fixing it :)

**Comment by nayuta-gondo** [comment]
It has been fixed. Please try it!

**Comment by fiatjaf** [comment]
It works! Thank you.
