### ISSUE TITLE
send commitment_signed before funding_locked received

### ISSUE THREAD

**Issue by nayuta-ueno** [nayutaco/ptarmigan#1449]
commit bb1815e4904d0e77637fbce349e7ffb925cf1f58 (pull request testing)

# sequence

peer: lnd

1. (establishing channel and wait confirmation)
2. disconnect
3. confirm !
4. reconnect
5. `init`, `channel_reestablish` exchanged
6. ptarmd send `funding_locked`, lnd not.
7. ptarmd create invoice
8. `lncli payinvoice`
9. [lnd --> ptarmd]update_add_htlc
10. [lnd --> ptarmd]commitment_signed
11. [ptarmd --> lnd]revoke_and_ack
12. [ptarmd --> lnd]commitment_signed

# result

lnd send `error`

```
rejected commitment
```

**Comment by nayuta-gondo** [comment]
おそらく`ln_channel_t::status`が`LN_STATUS_NORMAL_OPE`でなければ`ln_idle_proc`をスキップすればいいだろう。
