### ISSUE TITLE
fail connect to lnd node

### ISSUE THREAD

**Issue by nayuta-ueno** [nayutaco/ptarmigan#1641]
lnd send below `init` parameter:

```
-[init]-------------------------------
globalfeatures: 2200
localfeatures: 2281
  option_data_loss_protect:       2
  initial_routing_sync:           0
  option_upfront_shutdown_script: 2
  gossip_queries:                 0
--------------------------------
```

`var_onion_optin` is set to require bit.

**Comment by nayuta-gondo** [comment]
>Flags are numbered from the least-significant bit, at bit 0 (i.e. 0x1, an even bit).

**Comment by nayuta-ueno** [comment]
https://github.com/nayutaco/ptarmigan/commit/d894358bd78dbe316ae81ca20070f46fb85e81f6

globalfeatureがbit13以上にならないようにするという仕様もあったので、`uint16_t`で処理するようにした。幅が広がる場合には変更する必要あり。

**Comment by nayuta-ueno** [comment]
-[init]------------------------------
globalfeatures: 2200
features: 2281
  option_data_loss_protect:       1
  initial_routing_sync:           0
  option_upfront_shutdown_script: 0
  gossip_queries:                 2
  var_onion_optin:                2
  gossip_queries_ex:              0
  option_static_remotekey:        2
--------------------------------
```

**Comment by nayuta-ueno** [comment]
c-lightning

```
-[init]-----------------------------
globalfeatures: 2000
features: 28a2
  option_data_loss_protect:       2
  initial_routing_sync:           0
  option_upfront_shutdown_script: 2
  gossip_queries:                 2
  var_onion_optin:                0
  gossip_queries_ex:              2
  option_static_remotekey:        2
--------------------------------
```
