### ISSUE TITLE
minimum `feerate_per_kw`

### ISSUE THREAD

**Issue by nayuta-ueno** [nayutaco/ptarmigan#406]
`ptarmigan` uses 253 as the minimum` feerate_per_kw` (see `c-lightning`).
https://github.com/nayutaco/ptarmigan/blob/390a574353a3e849b4292572d030e3cf8213b9c3/ucoin/include/ln.h#L72

Is it OK ?
need check below:
* https://github.com/ElementsProject/lightning/issues/1443
* https://github.com/ElementsProject/lightning/issues/1391

**Comment by nayuta-ueno** [comment]
BOLTのfee計算がbitcoindと異なるためらしい。

https://lists.linuxfoundation.org/pipermail/lightning-dev/2018-May/001298.html

**Comment by ZmnSCPxj** [comment]
Also: https://github.com/ElementsProject/lightning/pull/1251
