### ISSUE TITLE
`ucoincli` too late

### ISSUE THREAD

**Issue by nayuta-ueno** [nayutaco/ptarmigan#443]
`ucoincli`の反応が非常に遅いことがある。
`-t`オプションを付けた場合にはすぐ反応しているので、`ucoind`との接続だと思われる。

**Comment by nayuta-ueno** [comment]
#452 によって解消することを期待したが、ダメだった。
telnetではすぐにconnectedになっているので、jsonrpc-cの問題だろうか？

`time` で見てみると、userもsysも時間がかかっていないので、どこかで待たされているようだ。

```
$ time ../ucoincli -l
{
        "result":       {
...(中略)...
}

real    2m55.296s
user    0m0.004s
sys     0m0.004s
```

**Comment by nayuta-ueno** [comment]
`-l`はそうでもない気がするが、`-r`が遅い気がする。

**Comment by nayuta-ueno** [comment]
最近気にならないので、close。

**Comment by nayuta-ueno** [comment]
まだ起きているようだ。
状況がよくわからないが、たぶんJSON-RPCのどこかで止まっているのだろう。
testnetで長時間動かしていると発生する？

**Comment by nayuta-gondo** [comment]
lmdbへのアクセスが競合
flags=0（RW）でオープンしたdbがcommit/abortするまでロックされる。
listinvoide methodでRWでアクセスするときにdbがロックされているので待たされる。
ロックしている処理はsend_announcement()。関数の呼び出しから完了までロックされる。
蓄積されたgossipデータが多くなるほど検索に時間を要している。

**Comment by nayuta-ueno** [comment]
listinvoiceはnode用のDBだが、announcementで何かしているのだろうか？
あるいは、このときは何かしていたのだろうか。
当時はannouncementとinvoiceを同じDBにしていたのかもしれない。
何にせよ、遅いときはDBがロックしているのが原因のようだから、今後も注意しよう。
