### ISSUE TITLE
data loss protection faild

### ISSUE THREAD

**Issue by nayuta-gondo** [nayutaco/ptarmigan#651]
対lndでうまくいかない。

lightning-integratonでは、
py.test -v test.py -s -k 'test_reconnect[ptarmigan_lnd]'
py.test -v test.py -s -k 'test_reconnect[lnd_ptarmigan]'
がfailed

lightning-integratonでは一旦data loss protectionを無効化しておく。

**Comment by nayuta-ueno** [comment]
再テスト

**Comment by nayuta-ueno** [comment]
commitment numberが不一致の場合、 `commitment_signed` の再送ができていない

**Comment by nayuta-ueno** [comment]
option_data_loss_protectよりも #546 の方が近いため、こちらは閉じる。
